backend:
  name: auth0
domain: dev-1uqulubqjqoqred6.us.auth0app.com
  clientId: 3Wc3HSUUhb26jUrIPzeRXET7cccMi8zm
  login: true
  redirectUri: https://agingdoghealth.com/admin/callback

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://www.agingdoghealth.com"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Description (SEO)", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Article"] }
      - { label: "Body", name: "body", widget: "markdown" }

publish_mode: editorial_workflow
